backend:
  name: git-gateway
  branch: main

media_folder: "site/static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "images/uploads" # The src attribute for uploaded media will begin with images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: nl
    label: Pages NL
    folder: site/content/nl
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Show in main menu", name: "menu", default: true, widget: "boolean"}
      - {label: "Menu order", name: "weight", widget: "number", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: en
    label: Pages EN
    folder: site/content/en
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Show in main menu", name: "menu", default: true, widget: "boolean"}
      - {label: "Menu order", name: "weight", widget: "number", required: false}
      - {label: "Body", name: "body", widget: "markdown"}